name: dbt ci

on:
  pull_request:
    branches: [duckdb]

jobs:
  dbt-build:
      name: dbt build
      runs-on: ubuntu-latest
      steps: 
        - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
        - name: Install uv
          uses: astral-sh/setup-uv@e58605a9b6da7c637471fab8847a5e5a6b8df081  # astral-sh/setup-uv@v5
        - name: dbt build
          run: |
            uv sync
            dbt build --select state:modified+ --state ./target